export interface NodeType {
  name: string;                    // Primary key from NodeType model
  inputDataType: string;
  outputDataType: string;
  allowedCycleTarget: string | null;
}

export interface PipelineNode {
  id?: string;                     // Generated by backend, not sent in creation
  name: string;                    // Unique within pipeline
  type: string;                    // References NodeType.name
  positionX: number;
  positionY: number;
}

export interface PipelineEdge {
  id?: string;                     // Generated by backend, not sent in creation
  fromNodeId?: string;             // Backend expects node ID, not name
  toNodeId?: string;               // Backend expects node ID, not name
  fromNodeName?: string;           // Alternative: frontend uses names for convenience
  toNodeName?: string;             // Alternative: frontend uses names for convenience
}

export interface Pipeline {
  id?: string;
  name: string;
  createdAt?: string;
  updatedAt?: string;
  nodes: PipelineNode[];
  edges: PipelineEdge[];
}

// React Flow specific types
export interface FlowNode {
  id: string;                      // We'll use temporary ID until saved
  type?: string;
  position: { x: number; y: number };
  data: {
    label: string;
    nodeType: string;
    nodeName: string;              // The unique name within pipeline
    backendId?: string;            // ID from backend after save
  };
}

export interface FlowEdge {
  id: string;
  source: string;                  // React Flow node ID (temporary)
  target: string;                  // React Flow node ID (temporary)
  sourceHandle?: string | null;
  targetHandle?: string | null;
}

// API Request/Response types
export interface CreatePipelineRequest {
  name: string;
  nodes: Array<{
    name: string;
    type: string;
    positionX: number;
    positionY: number;
  }>;
  edges: Array<{
    fromNodeName: string;          // Backend API expects node names!
    toNodeName: string;            // Not IDs, as shown in your API examples
  }>;
}

export interface UpdatePipelineRequest extends CreatePipelineRequest {
  id: string;
}

// Helper to convert between formats
export interface PipelineWithBackendIds extends Pipeline {
  nodes: Array<PipelineNode & { id: string }>;
  edges: Array<PipelineEdge & { id: string; fromNodeId: string; toNodeId: string }>;
}